# Generated by Django 2.0.2 on 2018-02-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, choices=[('Fantastic', 'FAN'), ('Sciencie-Fiction', 'SCF'), ('Thriller', 'THR'), ('Drama', 'DRA'), ('Action', 'ACT'), ('Comedy', 'COM'), ('Kids', 'KID'), ('Mistery', 'MIS'), ('Terror', 'TER'), ('Uncategoried', 'UNC')], default='UNC', max_length=3)),
                ('synopsis', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True)),
                ('movie_seen', models.BooleanField(default=False)),
                ('duration', models.IntegerField(blank=True, default='')),
            ],
        ),
    ]
