# Generated by Django 2.0.2 on 2018-02-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(blank=True, choices=[('FAN', 'Fantastic'), ('SCF', 'Sciencie-Fiction'), ('THR', 'Thriller'), ('DRA', 'Drama'), ('ACT', 'Action'), ('COM', 'Comedy'), ('KID', 'Kids'), ('MIS', 'Mistery'), ('TER', 'Terror'), ('UNC', 'Uncategoried')], default='UNC', max_length=3),
        ),
    ]
